import React from 'react';
declare const _default: {
    component: React.FC<import("./card").CardProps>;
    title: string;
};
export default _default;
export declare const createApreciationCard: () => JSX.Element;
export declare const appreciationCard: () => JSX.Element;
export declare const appreciationCardThumbnail: () => JSX.Element;
export declare const appreciationCardNotification: () => JSX.Element;
export declare const individualPersonCard: () => JSX.Element;
export declare const mapCard: () => JSX.Element;
export declare const articleCard: () => JSX.Element;
export declare const articleCardFeatured: () => JSX.Element;
export declare const articleCardFull: () => JSX.Element;
export declare const eventCard: () => JSX.Element;
export declare const minimalCard: () => JSX.Element;
export declare const eventCardFull: () => JSX.Element;
export declare const departmentCard: () => JSX.Element;
export declare const employeeServCard: () => JSX.Element;
export declare const notificationCard: () => JSX.Element;
export declare const approvalNotificationCard: () => JSX.Element;
export declare const eventCardList: () => JSX.Element;
export declare const eventCardEmbedded: () => JSX.Element;
export declare const cardsListsContainer: () => JSX.Element;
export declare const peopleCard: () => JSX.Element;
export declare const contactMeCard: () => JSX.Element;
export declare const myContacts: () => JSX.Element;
export declare const getToKnowMeCard: () => JSX.Element;
export declare const minimalNewsList: () => JSX.Element;
export declare const minimalNewsEmbedded: () => JSX.Element;
export declare const OfficesList: () => JSX.Element;
export declare const knowledgeBaseSearchCard: () => JSX.Element;
export declare const techCatalogSearchCard: () => JSX.Element;
export declare const linkSearchCard: () => JSX.Element;
export declare const documentSearchCard: () => JSX.Element;
export declare const departmentSearchCard: () => JSX.Element;
export declare const officeSearchCard: () => JSX.Element;
export declare const pageSearchCard: () => JSX.Element;
export declare const brandsLabelsCard: () => JSX.Element;
export declare const peopleSearchCard: () => JSX.Element;
export declare const articleSearchCard: () => JSX.Element;
//# sourceMappingURL=card.stories.d.ts.map