import React from 'react';
declare const _default: {
    component: React.FC<import("..").UIButtonProps>;
    title: string;
};
export default _default;
export declare const dateRangeHeader: () => JSX.Element;
export declare const allLinksButton: () => JSX.Element;
export declare const hamburgerButton: () => JSX.Element;
export declare const notificationsBadge: () => JSX.Element;
export declare const siteLogo: () => JSX.Element;
export declare const userBadge: () => JSX.Element;
export declare const closeButton: () => JSX.Element;
export declare const cancelButton: () => JSX.Element;
export declare const primaryButton: () => JSX.Element;
export declare const secondaryButton: () => JSX.Element;
export declare const uploadButton: () => JSX.Element;
export declare const checkBox: () => JSX.Element;
export declare const editButton: () => JSX.Element;
export declare const contentWrapper: () => JSX.Element;
export declare const noNotification: () => JSX.Element;
export declare const footerContainer: () => JSX.Element;
export declare const thumbButton: () => JSX.Element;
export declare const orgChart: () => JSX.Element;
export declare const expandButton: () => JSX.Element;
export declare const textbox: () => JSX.Element;
export declare const customCheckBox: () => JSX.Element;
export declare const buttonWithIcon: () => JSX.Element;
export declare const settingsButton: () => JSX.Element;
export declare const toastSuccess: () => JSX.Element;
export declare const toastError: () => JSX.Element;
export declare const error400: () => JSX.Element;
export declare const error401: () => JSX.Element;
export declare const error403: () => JSX.Element;
export declare const error404: () => JSX.Element;
export declare const error500: () => JSX.Element;
export declare const confirmationModal: () => JSX.Element;
export declare const alertModal: () => JSX.Element;
export declare const rejectModal: () => JSX.Element;
export declare const partition: () => JSX.Element;
//# sourceMappingURL=components.stories.d.ts.map